---
Name: DerrifordConfig
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - DorsetDigital\Themes\Derriford\Extension\ConfigExtension

PageController:
  extensions:
    - DorsetDigital\Themes\Derriford\Extension\PageControllerExtension

DorsetDigital\Themes\Derriford\Page\ContentPage:
  extensions:
  - DNADesign\Elemental\Extensions\ElementalPageExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
  - DorsetDigital\Themes\Derriford\Extension\SiteTreeThemeExtension
  - DorsetDigital\Themes\Derriford\Extension\PageExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\View\Requirements_Backend:
    class: DorsetDigital\Themes\Derriford\Extension\CustomRequirements

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - DorsetDigital\Themes\Derriford\Extension\ElementExtension