---
Name: CoreThemeConfig
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - DorsetDigital\Themes\Core\Extension\ConfigExtension

PageController:
  extensions:
    - DorsetDigital\Themes\Core\Extension\PageControllerExtension

DorsetDigital\Themes\Core\Page\ContentPage:
  extensions:
  - DNADesign\Elemental\Extensions\ElementalPageExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
  - DorsetDigital\Themes\Core\Extension\SiteTreeThemeExtension
  - DorsetDigital\Themes\Core\Extension\PageExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\View\Requirements_Backend:
    class: DorsetDigital\Themes\Core\Extension\CustomRequirements

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - DorsetDigital\Themes\Core\Extension\ElementExtension